admin_users: [554368298]
debug: false
display:
  language: zh
  style: detailed
limit:
  daily_max: 3
  reset_hour: 0
llm:
  api_base: 'https://api.deepseek.com/v1'
  api_key: 'sk-ddfb7995e3ac45b8b871a1d6f694dd41'
  api_type: deepseek
  enabled: true
  model: deepseek-chat
