admin_users: []
debug: false
display:
  language: zh
  style: detailed
limit:
  daily_max: 3
  reset_hour: 0
llm:
  api_base: ''
  api_key: ''
  api_type: openai
  enabled: false
  model: gpt-3.5-turbo
