apiVersion: v1
kind: Plugin
metadata:
  author: ydzat
  name: OracleLang
  repository: 'https://github.com/ydzat/OracleLang'
  version: 2.1.0
  description:
    en_US: 'An intelligent divination plugin based on I Ching principles. Supports multiple divination methods and provides professional hexagram interpretations.'
    zh_Hans: '一个基于易经原理的智能算卦插件。支持多种起卦方式,提供专业的卦象解读。'
  label:
    en_US: OracleLang
    zh_Hans: OracleLang 易经算卦
  icon: assets/icon.svg
spec:
  config:
    - name: daily_max
      type: integer
      label:
        en_US: Daily Divination Limit
        zh_Hans: 每日算卦次数限制
      description:
        en_US: Maximum number of divinations per user per day
        zh_Hans: 每位用户每天最多可以算卦的次数
      default: 3
      required: false

    - name: reset_hour
      type: integer
      label:
        en_US: Daily Reset Hour
        zh_Hans: 每日重置时间
      description:
        en_US: Hour of day to reset usage count (0-23, UTC+8)
        zh_Hans: 每日重置使用次数的时间点（0-23，东八区时间）
      default: 0
      required: false

    - name: llm_enabled
      type: boolean
      label:
        en_US: Enable LLM Interpretation
        zh_Hans: 启用大模型解释
      description:
        en_US: Use LLM configured in LangBot to provide enhanced hexagram interpretations
        zh_Hans: 使用 LangBot 中配置的大语言模型提供增强的卦象解释
      default: true
      required: false

    - name: display_style
      type: select
      label:
        en_US: Hexagram Display Style
        zh_Hans: 卦象显示风格
      description:
        en_US: Visual style for displaying hexagrams
        zh_Hans: 卦象的视觉显示风格
      options:
        - name: simple
          label:
            en_US: Simple
            zh_Hans: 简洁
        - name: traditional
          label:
            en_US: Traditional
            zh_Hans: 传统
        - name: detailed
          label:
            en_US: Detailed
            zh_Hans: 详细
      default: detailed
      required: false

    - name: admin_users
      type: array[string]
      label:
        en_US: Admin User IDs
        zh_Hans: 管理员用户ID列表
      description:
        en_US: List of user IDs with admin privileges
        zh_Hans: 拥有管理员权限的用户ID列表
      default: []
      required: false

    - name: debug
      type: boolean
      label:
        en_US: Debug Mode
        zh_Hans: 调试模式
      description:
        en_US: Enable debug output
        zh_Hans: 启用调试输出
      default: false
      required: false

    - name: timezone
      type: string
      label:
        en_US: Timezone
        zh_Hans: 时区
      description:
        en_US: Timezone for daily reset (e.g., Asia/Shanghai, America/New_York, Europe/London)
        zh_Hans: 每日重置使用的时区（如 Asia/Shanghai、America/New_York、Europe/London）
      default: 'Asia/Shanghai'
      required: false

  components:
    Command:
      fromDirs:
      - path: components/commands/

execution:
  python:
    path: main.py
    attr: OracleLangPlugin