apiVersion: v1
kind: EventListener
metadata:
  name: default
  description:
    en_US: 'Default event listener for OracleLang plugin'
    zh_Hans: 'OracleLang插件的默认事件监听器'
  label:
    en_US: Default Event Listener
    zh_Hans: 默认事件监听器
spec:
  config: []
execution:
  python:
    path: default.py
    attr: DefaultEventListener

